### ISSUE TITLE
Provide a metric exposing number of packages that were requested by a user but were not found as solved

### ISSUE THREAD

**Issue by fridex** [thoth-station/metrics-exporter#724]
**Is your feature request related to a problem? Please describe.**

As a Thoth operator, I would like to know how many requests made to the system failed on an unsolved package. For this, I would like to observe a metric - the number of advisers that failed due to an unsolved package and correlate it to number of total adviser runs.

Can read as:

> X% of advisers failed on unsolved package

This will expose how the data stored in the system are supporting Thoth user needs.

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> As a Thoth operator, I would like to know how many requests made to the system failed on an unsolved package. For this, I would like to observe a metric - the number of advisers that failed due to an unsolved package and correlate it to number of total adviser runs.
> 
> Can read as:
> 
> > X% of advisers failed on unsolved package
> 
> This will expose how the data stored in the system are supporting Thoth user needs.

We already collect every day this in adviser-reporter and store in on Ceph. We can also send these metrics to pushgateway to have them in Grafana since there is no ETA on Superset. wdyt?

On Grafana currently we can see the number of unresolved messages sent by adviser workflow and exposed by investigator. This is shown in in the dashboards already: https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/6576535a8b26fd1a0e5328f4413dfd8bc989f54f/thoth-kafka-consumers-and-argo-workflows?orgId=1&refresh=30s. This cannot be used for the metric requested in the issue though.

**Comment by pacospace** [comment]
Same as https://github.com/thoth-station/metrics-exporter/issues/725#issuecomment-870762950 we can see the percentage of failed workflows and the reason, including if it is due to unresolved which is https://thoth-station.ninja/j/unresolved.html if I'm correct? wdyt?

**Comment by fridex** [comment]
> Same as [#725 (comment)](https://github.com/thoth-station/metrics-exporter/issues/725#issuecomment-870762950) we can see the percentage of failed workflows and the reason, including if it is due to unresolved which is https://thoth-station.ninja/j/unresolved.html if I'm correct? wdyt @fridex ?

Nice! Then I think this can be considered as done. 👍🏻 

/close
